# Generated by Django 6.0.7 on 2026-08-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_task_color_task_updated_at_alter_task_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_color',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('School', 'School'), ('Personal', 'Personal'), ('Work', 'Work'), ('Others', 'Others')], default='Personal', max_length=100),
        ),
    ]
